build:
  maxIssues: 0

processors:
  active: false

potential-bugs:
  active: true
  Deprecation:
    active: false #todo https://github.com/arturbosch/detekt/issues/2038
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: false #todo https://github.com/arturbosch/detekt/issues/2042
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: false
    excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
    excludeAnnotatedProperties: ""
    ignoreOnClassesPattern: "" #todo
  MissingWhenCase:
    active: false #todo https://github.com/arturbosch/detekt/issues/2041
  RedundantElseInWhen:
    active: fasle #todo https://github.com/arturbosch/detekt/issues/2041
  UnconditionalJumpStatementInLoop:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: false #todo https://github.com/arturbosch/detekt/issues/2043
  UnsafeCast:
    active: false #todo https://github.com/arturbosch/detekt/issues/2043
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true
